# -*- coding: utf-8 -*-
"""histograma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i9DlqM1ZMhkeod02pMK3qoWdUz4sIXe1
"""

import matplotlib.pyplot as plt
import numpy as np

img = plt.imread("pocoyo.jpg")

img.shape

plt.figure()
plt.imshow(img)
plt.title("El famoso Pocoyo")
plt.axis("off")

imgR = img[:,:,0]
imgG = img[:,:,1]
imgB = img[:,:,2]

np.max(img), np.min(img)

plt.figure()

fig, (ax1,ax2,ax3) = plt.subplots(1,3,figsize=(12,4))

#ax1.imshow(imgR, cmap="gray")
ax1.imshow(imgR)
ax1.axis("off")
ax1.set_title("pocoyo: Canal rojo")

#ax2.imshow(imgG, cmap="gray")
ax2.imshow(imgG)
ax2.axis("off")
ax2.set_title("pocoyo: Canal verde")

#ax3.imshow(imgB, cmap="gray")
ax3.imshow(imgB)
ax3.axis("off")
ax3.set_title("pocoyo: Canal azul")

plt.show()

# Obtener las dimensiones de la imagen
# h: altura, w: ancho, c: canales (profundidad)
h, w, c = img.shape

# Crear una matriz de h filas y w columnas de ceros
pocoyo_gris1 = np.zeros((h,w))

sum_valor_canales = 0

# Para cada fila de la imagen
for i in range(h):
  # Para cada columna de la imagen
  for j in range(w):
    # Para cada canal de la imagen
    for k in range(c):
      # Sumar el dato de los valores de cada canal 
      # para cada pixel ubicado en i, j 
      sum_valor_canales += img[i][j][k]
    # Calcular el promedio de cada pixel
    sum_valor_canales = sum_valor_canales / 3

    pocoyo_gris1[i][j] =  sum_valor_canales
    sum_valor_canales = 0

pocoyo_gris1.shape

plt.figure()
plt.imshow(pocoyo_gris1, cmap="gray")

"""VECTORIZADA"""

# Obtener las dimensiones de la imagen
# h: altura, w: ancho, c: canales (profundidad)
h, w, c = img.shape

# Crear una matriz de h filas y w columnas de ceros
pocoyo_gris2v1 = np.zeros((h,w))

pocoyo_gris2v1 = img[:,:,0]/3 + img[:,:,1]/3 + img[:,:,2]/3

plt.figure()
plt.imshow(pocoyo_gris2v1, cmap="gray")

"""MÉTODO 2"""

pocoyo_gris2v2 = np.mean(img, axis=2)

plt.figure()
plt.imshow(pocoyo_gris2v2, cmap="gray")

"""HISTOGRAMA ESCALA DE GRISES"""

plt.figure(figsize=(12,5))
plt.subplot(121)
plt.hist(pocoyo_gris2v1,histtype="stepfilled",facecolor="gray")
plt.subplot(122)
plt.hist(pocoyo_gris2v2,histtype="stepfilled",facecolor="gray")
plt.show()

"""HISTOGRAMA ESCALA DE COLOR"""

plt.figure()

fig, (ax1,ax2,ax3) = plt.subplots(1,3,figsize=(12,4))

ax1.hist(imgR,histtype="stepfilled",facecolor="red")
ax1.set_title("pocoyo: Histograma Canal rojo")

ax2.hist(imgG,histtype="stepfilled",facecolor="green")
ax2.set_title("pocoyo: Histograma Canal verde")

ax3.hist(imgB,histtype="stepfilled",facecolor="blue")
ax3.set_title("pocoyo: Histograma Canal azul")

plt.show()